import {
  Laptop,
  Smartphone,
  Headphones,
  Shirt,
  Car,
  Home,
  ShirtIcon as TShirt,
  FootprintsIcon as Shoes,
  ShoppingBag,
  Crown,
  CarFront,
  Bike,
  Sofa,
  Bed,
  Lamp,
  Target,
  Camera,
  Tv,
  Book,
  Gem,
  Dumbbell,
  Palette,
  Wrench,
} from "lucide-react"

export const categoriesData = [
  {
    id: "electronics",
    name: "Electronics",
    icon: <Laptop className="h-6 w-6" />,
    types: [
      {
        id: "smartphones",
        name: "Smartphones & Tablets",
        description: "Latest mobile devices and tablets",
        icon: <Smartphone className="h-5 w-5" />,
        count: 1247,
      },
      {
        id: "computers",
        name: "Computers & Laptops",
        description: "Desktop PCs, laptops, and accessories",
        icon: <Laptop className="h-5 w-5" />,
        count: 892,
      },
      {
        id: "audio",
        name: "Audio & Headphones",
        description: "Headphones, speakers, and sound systems",
        icon: <Headphones className="h-5 w-5" />,
        count: 634,
      },
      {
        id: "cameras",
        name: "Cameras & Photography",
        description: "Digital cameras, lenses, and equipment",
        icon: <Camera className="h-5 w-5" />,
        count: 423,
      },
      {
        id: "tv-home-theater",
        name: "TV & Home Theater",
        description: "Smart TVs, streaming devices, and sound bars",
        icon: <Tv className="h-5 w-5" />,
        count: 356,
      },
    ],
  },
  {
    id: "fashion",
    name: "Fashion & Apparel",
    icon: <Shirt className="h-6 w-6" />,
    types: [
      {
        id: "mens-clothing",
        name: "Men's Clothing",
        description: "Shirts, pants, suits, and casual wear",
        icon: <TShirt className="h-5 w-5" />,
        count: 2156,
      },
      {
        id: "womens-clothing",
        name: "Women's Clothing",
        description: "Dresses, tops, bottoms, and formal wear",
        icon: <Gem className="h-5 w-5" />,
        count: 3247,
      },
      {
        id: "shoes",
        name: "Shoes & Footwear",
        description: "Sneakers, boots, heels, and athletic shoes",
        icon: <Shoes className="h-5 w-5" />,
        count: 1834,
      },
      {
        id: "accessories",
        name: "Accessories",
        description: "Bags, belts, hats, and jewelry",
        icon: <ShoppingBag className="h-5 w-5" />,
        count: 967,
      },
      {
        id: "luxury",
        name: "Luxury & Designer",
        description: "Premium brands and designer collections",
        icon: <Crown className="h-5 w-5" />,
        count: 445,
      },
    ],
  },
  {
    id: "home-garden",
    name: "Home & Garden",
    icon: <Home className="h-6 w-6" />,
    types: [
      {
        id: "furniture",
        name: "Furniture",
        description: "Sofas, chairs, tables, and storage",
        icon: <Sofa className="h-5 w-5" />,
        count: 1456,
      },
      {
        id: "bedroom",
        name: "Bedroom",
        description: "Beds, mattresses, and bedroom decor",
        icon: <Bed className="h-5 w-5" />,
        count: 834,
      },
      {
        id: "lighting",
        name: "Lighting & Electrical",
        description: "Lamps, fixtures, and electrical supplies",
        icon: <Lamp className="h-5 w-5" />,
        count: 567,
      },
      {
        id: "kitchen",
        name: "Kitchen & Dining",
        description: "Appliances, cookware, and dining sets",
        icon: <Wrench className="h-5 w-5" />,
        count: 1234,
      },
    ],
  },
  {
    id: "automotive",
    name: "Automotive",
    icon: <Car className="h-6 w-6" />,
    types: [
      {
        id: "car-parts",
        name: "Car Parts & Accessories",
        description: "Engine parts, filters, and car accessories",
        icon: <Target className="h-5 w-5" />,
        count: 2341,
      },
      {
        id: "tires",
        name: "Tires & Wheels",
        description: "All-season, winter, and performance tires",
        icon: <CarFront className="h-5 w-5" />,
        count: 567,
      },
      {
        id: "motorcycles",
        name: "Motorcycles & ATVs",
        description: "Bikes, scooters, and off-road vehicles",
        icon: <Bike className="h-5 w-5" />,
        count: 234,
      },
    ],
  },
  {
    id: "books-media",
    name: "Books & Media",
    icon: <Book className="h-6 w-6" />,
    types: [
      {
        id: "books",
        name: "Books",
        description: "Fiction, non-fiction, and educational books",
        icon: <Book className="h-5 w-5" />,
        count: 45678,
      },
      {
        id: "music",
        name: "Music",
        description: "CDs, vinyl records, and digital music",
        icon: <Headphones className="h-5 w-5" />,
        count: 2345,
      },
    ],
  },
  {
    id: "health-beauty",
    name: "Health & Beauty",
    icon: <Gem className="h-6 w-6" />,
    types: [
      {
        id: "skincare",
        name: "Skincare",
        description: "Cleansers, moisturizers, and treatments",
        icon: <Gem className="h-5 w-5" />,
        count: 1234,
      },
      {
        id: "makeup",
        name: "Makeup & Cosmetics",
        description: "Foundation, lipstick, and beauty tools",
        icon: <Palette className="h-5 w-5" />,
        count: 2345,
      },
      {
        id: "health",
        name: "Health & Wellness",
        description: "Vitamins, supplements, and health products",
        icon: <Dumbbell className="h-5 w-5" />,
        count: 876,
      },
    ],
  },
]
