import type { Metadata } from "next";
import { inter, oxanium } from "@/app/fonts";
import "@/app/globals.css";
import AuthProvider from "@/components/authentication/AuthProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Navbar from "@/components/customerUI/navbar/navbar";
import getSections from "@/utils/getSections";

export const metadata: Metadata = {
  title: "Motoshop",
  description: "Generated by create next app",
};

//f// Layout ------------------------------------------------------------------------------------
export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const sections = await getSections();
  return (
    <html lang='en' className={`${inter.variable} ${oxanium.variable}`}>
      <AuthProvider>
        <body className='bg-grey-light'>
          <NuqsAdapter>
            <Navbar sections={sections} />
            {children}
          </NuqsAdapter>
        </body>
      </AuthProvider>
    </html>
  );
}
