import type { Metadata } from "next";
import { inter, oxanium } from '@/app/fonts';
import "@/app/globals.css";
import AuthProvider from "@/components/authentication/AuthProvider";
import NavBar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Motoshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.variable} ${oxanium.variable}`}>
      <AuthProvider>
        <body>

          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
