import type { Metadata } from "next";
import { inter, oxanium } from './fonts';
import "./globals.css";
import AuthProvider from "@/components/authentication/AuthProvider";
import NavBar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Motoshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.variable} ${oxanium.variable}`}>
      <AuthProvider>
        <body>
          <NavBar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
